SYNC_WORD = b"\xAA\xBB"
SYNC_WORD_SIZE = len(SYNC_WORD)
FRAME_ID_SIZE = 4
PAYLOAD_LEN_SIZE = 2
HEADER_SIZE = SYNC_WORD_SIZE + FRAME_ID_SIZE + PAYLOAD_LEN_SIZE
CRC_SIZE = 4
MIN_FRAME_SIZE = HEADER_SIZE + CRC_SIZE
