apiVersion: 1

datasources:
  - name: TimescaleDB
    type: postgres
    access: proxy
    url: timescaledb:5432
    database: telemetry
    user: astro
    jsonData:
      sslmode: disable
      timescaledb: true
    secureJsonData:
      password: astro
    isDefault: true
    editable: false
