apiVersion: 1

datasources:
  - name: TimescaleDB
    uid: TimescaleDB
    type: grafana-postgresql-datasource
    access: proxy
    url: timescaledb:5432
    database: telemetry
    user: astro
    jsonData:
      sslmode: disable
      timescaledb: true
    secureJsonData:
      password: astro
    isDefault: true
    editable: false

  - name: Prometheus
    uid: Prometheus
    type: prometheus
    access: proxy
    url: http://prometheus:9090
    isDefault: false
    editable: false
